In [20]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
#importing the libraries

In [5]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [6]:
import tensorflow as tf

In [8]:
tf.__version__

'2.10.0'

In [ ]:
#importing dataset

In [9]:
dataset = pd.read_csv('Churn_Modelling.csv') #loading the dataset
X = dataset.iloc[:, 3:-1].values #the 3 signifies the column n0. from the ddataset that we r considering.....i.e, the first 3 columns are of no use in calculation
y = dataset.iloc[:, -1].values #this is the column used for the output i.e y.....i.e is the last column which tells weather the customer leaves or not

In [10]:
print(dataset)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMemb

In [12]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
#encoding for gender (lable encoding for dependent variable)

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
# 0 is for female and 1 is for male

In [14]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
# as we cant make the country values as 0 and 1 we need to use onehot encoding 

In [16]:
'''from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough'
X = np.array(ct.fit_transform(X))'''
#the only thing that needs to b changed in the code is the column index i.e,in place of 0 change it to the desired column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [17]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
#splitting the dataset 

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
#feature scaling
#very important to do it for deep learning

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building the ann

In [ ]:
#initializing the ann

In [21]:
ann = tf.keras.models.Sequential()

In [ ]:
#adding the first intermediate layer

In [22]:
ann.add(tf.keras.layers.Dense(units = 6,activation = "relu"))

In [ ]:
#adding the second intermediate layer


In [23]:
ann.add(tf.keras.layers.Dense(units = 6,activation = "relu"))

In [ ]:
#adding the output layer

In [24]:
ann.add(tf.keras.layers.Dense(units = 1,activation = "sigmoid"))

# Training the ann


In [ ]:
#compiling the ann

In [25]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [ ]:
#training the ann

In [26]:
ann.fit(X_train,y_train,batch_size = 32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 7s 2ms/step - loss: 0.5237 - accuracy: 0.7959
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4555 - accuracy: 0.8045
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4358 - accuracy: 0.8079
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4289 - accuracy: 0.8112
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4253 - accuracy: 0.8145
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4219 - accuracy: 0.8150
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4194 - accuracy: 0.8181
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4166 - accuracy: 0.8219
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4139 - accuracy: 0.8242
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4107 - accura

250/250 [==============================] - 1s 2ms/step - loss: 0.3369 - accuracy: 0.8633
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3375 - accuracy: 0.8621
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3377 - accuracy: 0.8614
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3373 - accuracy: 0.8604
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3373 - accuracy: 0.8610
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3374 - accuracy: 0.8633
Epoch 87/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3376 - accuracy: 0.8609
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3371 - accuracy: 0.8604
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3369 - accuracy: 0.8621
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3369 - accuracy: 

In [ ]:
#predicting the output

In [29]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)
#the false indicates that the customer will not leave the bank 

1/1 [==============================] - 0s 9ms/step
[[False]]


In [30]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))
#can also be written like this
#the number 0.05 tells that the probablility of the customer leaving the bank is 0.05

1/1 [==============================] - 0s 25ms/step
[[0.05169033]]


# Predicting the test results

In [ ]:
##use any model

In [31]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
#pasted from knn instead of the classifier variable ann is used 

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
#in the above code cell we can see [0 0] this means that the predicted value and the actual value r the same for customer 1
#but for customer 2 it is diff and so on

# confusion matrix

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1528   67]
 [ 215  190]]


0.859

In [ ]:
#the accuracy is 86 percent